---
- hosts: 127.0.0.1
  connection: local
  become: yes
  become_method: sudo

  tasks:
   - name: Install python3
     apt: pkg=python3 state=installed update_cache=true

   - name: Delete default Postgresql configuration file
     shell: rm /etc/postgresql/9.5/main/pg_hba.conf
     ignore_errors: yes

   - name: Copy postgresql config file
     copy: src={{item.src}} dest={{item.dest}}
     with_items:
       - {src: './config/idps/pg_hba.conf', dest: '/etc/postgresql/9.5/main/'}

   - name: Install supervisor
     apt: pkg=supervisor state=installed update_cache=true

   - name: Get current working directory
     shell: "pwd"
     register: dir

   - name: Update python script location in supervisor conf
     lineinfile:
        path: ./config/idps/log_parser.conf
        regexp: '^command='
        line: 'command=python3 {{dir.stdout}}/config/idps/log_parser.py {{dir.stdout}}'

   - name: Copy supervisor config file
     copy: src={{ item.src }} dest={{ item.dest }}
     with_items:
       - { src: './config/idps/log_parser.conf', dest: '/etc/supervisor/conf.d/' }

   - name: Register service with supervisor
     command: supervisorctl reread

   - name: Update supervisorctl
     command: supervisorctl update

   - name: Restart Supervisor
     service: name=supervisor state=restarted
     become: yes

   - name: Install Fail2ban
     apt: pkg=fail2ban state=installed update_cache=true

   - name: Copy configuration files
     copy: src={{ item.src }} dest={{ item.dest }}
     with_items:
       - { src: './config/idps/jail.local', dest: '/etc/fail2ban/' }
       - { src: './config/idps/middleware.conf', dest: '/etc/fail2ban/filter.d/' }
       - { src: './config/idps/iptables-middleware.conf', dest: '/etc/fail2ban/action.d/' }

     become: yes

   - name: Restart Fail2ban
     service: name=fail2ban state=restarted
     become: yes
