---
# Use this for creation of the apt-repository.
  - name: Create .gnupg directory
    file: path=/root/.gnupg state=directory

  - name: Copy gpg.conf file
    copy:
      src: ./config/apt_repo/gpg.conf
      dest: /root/.gnupg/gpg.conf
      mode: 0644

  - name: Copy foo file
    copy:
      src: ./config/apt_repo/foo
      dest: /root/foo
      mode: 0600

  - name: Generate GPG key
    shell: gpg --batch --gen-key /root/foo

  - name: Remove foo file
    file: path=/root/foo state=absent

  - name: Create public key
    shell: gpg --export --armor > ansible.pub

  - name: Fetch apt-repo's GPG public key
    fetch:
      src: '/root/ansible.pub'
      dest: 'config/apt_repo/keys/ansible.pub'
      flat: yes

  - name: Get debian files of all packages and dependencies
    shell: 'apt-get -o Dir::Cache::Archives=/root/ -d -y install {{ item }}'
    with_items: ['git', 'nano','vim', 'python-pip', 'nodejs', 'npm', 'supervisor', 'iptables', 'bind9', 'openntpd', 'openjdk-8-jdk', 'slapd',
     'ldap-utils','perl','procps','openssl', 'libpcre3','apt-transport-https','postgresql','postgresql-contrib',
     'pkg-config', 'qtbase5-dev', 'libzmq3-dev', 'software-properties-common', 'locales', 'mongrel2-core','zurl']
#    with_items: ['git']

  - name: Install aptly
    apt: name=aptly state=present

  - name: Install python-pip
    apt: name=python-pip state=present

  - name: Create ansible repo in aptly
    shell: aptly -distribution="xenial" -architectures=amd64 repo create ansible

  - name: Add .deb files to ansible repo
    shell: aptly repo add ansible /root/
    tags: addrepo

  - name: Create a snapshot named ansible-repo of ansible repo (no more changes)
    shell: aptly snapshot create ansible-repo from repo ansible
    tags: addrepo

  - name: Ansible expect python dependency:- pexpect
    pip: name=pexpect state=present

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Install supervisor
    apt: name=supervisor state=present

  - name: Copy apt_repo.conf
    copy:
      src: config/apt_repo/supervisor-apt-repo.conf
      dest: /etc/supervisor/conf.d/supervisor-apt-repo.conf
      mode: 0644