---
# NOT REQUIRED IN THE READYTOSERVE IMAGE
#  - name: Publish snapshot ansible-repo
#    expect:
#      command: aptly -architectures=amd64 publish snapshot ansible-repo
#      responses:
#        passphrase: 'ansible'
#    ignore_errors: True

  - name: Start supervisor
    service: name=supervisor state=started
    become: yes
    become_user: root

  - name: Reload supervisorctl
    shell: supervisorctl reload
    become: yes
    become_user: root
