---
# Allows UDP packets from the kong machine for DNS purpose of Ansible installation.
- hosts: kong
  remote_user: root
  vars_files:
    - ../../host_vars/all
    - ../../host_vars/kong
  tasks:
  - name: Allow all incoming UDP packets
    shell: iptables -R INPUT 6 -p udp -j ACCEPT
    tags:
      - allow_udp

  - name: Allow all outgoing UDP packets
    shell: iptables -R OUTPUT 2 -p udp -j ACCEPT
    tags:
      - allow_udp