---
# Allows new connections from the kong machine
- hosts: kong
  remote_user: root
  vars_files:
    - ../../host_vars/all
    - ../../host_vars/kong
  tasks:
  - name: Allow all outgoing connections
    shell: iptables -P OUTPUT ACCEPT
    tags:
      - allow_outgoing