---
# Deny all UDP packets in the kong machine
- hosts: kong
  remote_user: root
  vars_files:
    - ../../host_vars/all
    - ../../host_vars/kong
  tasks:
  - name: Deny all incoming UDP packets
    shell: iptables -R INPUT 6 -p udp -j REJECT  --reject-with icmp-port-unreachable
    tags:
      - deny_udp

  - name: Deny all outgoing UDP packets
    shell: iptables -R OUTPUT 2 -p udp -j DROP
    tags:
      - deny_udp