---
# Deny all outgoing new packets. Allowed established, related outgoing packets.
- hosts: kong
  remote_user: root
  vars_files:
    - ../../host_vars/all
    - ../../host_vars/kong
  tasks:
  - name: Deny all outgoing packets except ESTABLISHED, RELATED
    shell: iptables -P OUTPUT DROP
    tags:
      - deny_outgoing