---
# kong iptables setup
- hosts: kong
  remote_user: root
  tasks:

  - name: Install Iptables
    apt: name=iptables state=present

  - name: Copy iptables config file to kong
    copy:
      src: ./config/kong/iptables-save
      dest: /root/iptables-rules
      mode: 0644
    tags:
      - iptables_copy

  - name: Apply rules in iptables
    shell: iptables-restore < iptables-rules
    tags:
      - iptables_apply


