### STORM Config

yaml storm.zookeeper.servers:
  - "localhost"

yaml nimbus.host: "localhost"
ui.port: 8000
yaml supervisor.slots.ports:
 - 6700
 - 6701
 - 6702
 - 6703

yaml storm.local.dir: "/tmp/storm"